services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: unless-stopped

  api:
    image: api
    build: .
    ports:
      - 127.0.0.1:8000:8000
    environment:
     - DATABASE_URL=${DATABASE_URL}
     - PREAUTH_TOKEN_EXPIRE=${PREAUTH_TOKEN_EXPIRE}
     - JWT_SECRET_KEY=${JWT_SECRET_KEY}
     - ALGORITHM=${ALGORITHM}
     - JWT_TOKEN_EXPIRE=${JWT_TOKEN_EXPIRE}
     - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
     - RECAPTCHAV2_SECRET_KEY=${RECAPTCHAV2_SECRET_KEY}
    depends_on:
     - postgres
    restart: unless-stopped
  
  redis:
    image: redis:8.2
    ports:
      - 127.0.0.1:6379:6379

volumes:
  postgres_data: